### ISSUE TITLE
[Yenepoya][Support] Relationship fixes

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#103]
- [x] **ticket -** https://avni.freshdesk.com/a/tickets/1115

- There are some relations showing twice. remove duplicate relations.
- Add relations - 
1. Son-in-law
2. Daughter-in-law
3. Grand mother

**Comment by nupoorkhandelwal** [comment]
**Both the changes are done. But there is bug in app, it displays voided relationships. So there are still duplicates showing in app. Moving this card on Hold till the bug is fixed.**

https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/avni-client/429


@garimadosar5  Meanwhile we can QA the worklist flow and reply them on the respective ticket. - Moved this to separate card and will move that card. #104

**Comment by garimadosar5** [comment]
- Very few relations are showing on the client app.
- Also, we need to check if there is any data with the voided relationship.
![Screenshot_2021-03-03-13-19-59-33_e67de974eab1ae435bf1faa372eb4549.jpg](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/6a81b385-e7a8-4863-9efa-3559d6098c36)
