### ISSUE TITLE
[Yenepoya][Report] Children Reports

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#31]
https://docs.google.com/spreadsheets/d/1yeUky6eZKLEBl89gj0UabxAMMsnpGUBHUNxolxDLYnE/edit#gid=2123379526

For all aggregate reports please note that following patterns are to be followed
1. Coded answers with 0 values should also appear
2. One of the indicators should be "Not responded", so that the tally matches
3. There should be total displayed where it shows the total count and total percentage tallying to 100% (except multi-select type questions).

**QA CHECKLIST**
- [ ] percentage Calculation
- [ ] Check for Column name and Indicator Name
- [ ] Check for 100% sun for percentage, if applicable
- [ ] Line List - Check for all the columns
- [ ] Line List - Column names are as mentioned in requirement sheet.
- [ ] Individual and Household cases are pointed to UAT.

**Comment by vindeolal** [comment]
**Aggregate report**
- Decimal places are not getting calculated in the %. Sum of the first 3 rows in % should always be 100%. Correct % will be 63.63%, 27.28% and 9.09%. Same goes with other rows as well.
- Logic for ARI is wrong, use correct observation from enrolment. (Change dynamic_where and LL report also accordingly)
- Report is not using the latest value, Check the case https://app.avniproject.org/#/app/subject/viewProgramEncounter?uuid=3d6d00bf-9d96-45a3-9ddc-5c848a73f201
For this case Health state of child is normal in the latest Child growth followup, but it shows up in ``` 	Children with deficiencies``` indicator.


**LL report**
- Exit/Non-exit filter is missing.
- Increase the width of ```Mobile number``` column so that 10 digits come in the same row. Same thing for ```Exit status``` column.
- Hide Dynamic where param or make it non-editable.
